import { afterEach, describe, expect, it } from "vitest";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  purgeLocalData,
  resolveRecallDataDir,
} from "../src/data/purge.js";

const originalDataDir = process.env.RECALL_DATA_DIR;

afterEach(() => {
  if (originalDataDir === undefined) {
    delete process.env.RECALL_DATA_DIR;
  } else {
    process.env.RECALL_DATA_DIR = originalDataDir;
  }
});

describe("local data purge", () => {
  it("dry-runs without deleting data or generated context", () => {
    const fixture = makeFixture();

    const result = purgeLocalData({
      dataDir: fixture.dataDir,
      dryRun: true,
      homeDir: fixture.home,
      keepIntegrations: true,
      repoRoots: [fixture.projects],
    });

    expect(result.dry_run).toBe(true);
    expect(result.failures).toBe(0);
    expect(existsSync(fixture.dataFile)).toBe(true);
    expect(existsSync(fixture.generatedContext)).toBe(true);
    expect(result.actions).toContainEqual(expect.objectContaining({
      category: "data",
      target: fixture.dataDir,
      status: "planned",
    }));
  });

  it("deletes the whole data directory and only Recall-generated context", () => {
    const fixture = makeFixture();

    const result = purgeLocalData({
      dataDir: fixture.dataDir,
      homeDir: fixture.home,
      keepIntegrations: true,
      repoRoots: [fixture.projects],
    });

    expect(result.failures).toBe(0);
    expect(existsSync(fixture.dataDir)).toBe(false);
    expect(existsSync(fixture.generatedContext)).toBe(false);
    expect(readFileSync(fixture.userContext, "utf8")).toBe("# My notes\n");
  });

  it("is idempotent when local data is already absent", () => {
    const fixture = makeFixture();
    const options = {
      dataDir: fixture.dataDir,
      homeDir: fixture.home,
      keepIntegrations: true,
      repoRoots: [fixture.projects],
    };

    purgeLocalData(options);
    const second = purgeLocalData(options);

    expect(second.failures).toBe(0);
    expect(second.actions).toContainEqual(expect.objectContaining({
      category: "data",
      target: fixture.dataDir,
      status: "absent",
    }));
  });

  it("refuses filesystem and home directory targets", () => {
    const home = mkdtempSync(join(tmpdir(), "recall-purge-home-"));
    expect(() => purgeLocalData({
      dataDir: home,
      homeDir: home,
      keepIntegrations: true,
      repoRoots: [],
    })).toThrow(/unsafe Recall data directory/);
    expect(() => purgeLocalData({
      dataDir: "/",
      homeDir: home,
      keepIntegrations: true,
      repoRoots: [],
    })).toThrow(/unsafe Recall data directory/);
  });

  it("resolves the default under the selected home without creating it", () => {
    const home = mkdtempSync(join(tmpdir(), "recall-purge-home-"));
    delete process.env.RECALL_DATA_DIR;
    const path = resolveRecallDataDir({ homeDir: home });

    expect(path).toBe(join(home, ".recall"));
    expect(existsSync(path)).toBe(false);
  });
});

function makeFixture() {
  const home = mkdtempSync(join(tmpdir(), "recall-purge-home-"));
  const projects = join(home, "Projects");
  const generatedRepo = join(projects, "generated");
  const userRepo = join(projects, "user");
  const generatedContext = join(generatedRepo, ".recall", "context.md");
  const userContext = join(userRepo, ".recall", "context.md");
  const dataDir = join(home, ".recall");
  const dataFile = join(dataDir, "backups", "2026-07-28.db");

  for (const repo of [generatedRepo, userRepo]) {
    mkdirSync(join(repo, ".git"), { recursive: true });
    mkdirSync(join(repo, ".recall"), { recursive: true });
  }
  mkdirSync(join(dataDir, "backups"), { recursive: true });
  writeFileSync(dataFile, "private memory");
  writeFileSync(
    generatedContext,
    "<!-- Auto-generated by Recall. Do not edit manually. -->\n# Recall Context\n",
  );
  writeFileSync(userContext, "# My notes\n");

  return {
    home,
    projects,
    generatedContext,
    userContext,
    dataDir,
    dataFile,
  };
}
