import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import type { RecallDb } from "../db/client.js";
import { exportMarkdown } from "../adapters/markdown.js";
import { inferRepoSlugFromPath, resolveLocalRepoPath } from "../repo/discovery.js";

export interface RepoContextArtifactResult {
  repo: string | null;
  repo_path: string | null;
  output_path: string | null;
  written: boolean;
}

export function getRepoContextArtifactPath(repoPath: string): string {
  return join(repoPath, ".recall", "context.md");
}

export function renderRepoContextArtifact(db: RecallDb, repo: string): string {
  const compiled = exportMarkdown(db, repo).trimEnd();
  const generatedAt = new Date().toISOString();

  return [
    "<!-- Auto-generated by Recall. Do not edit manually. -->",
    `<!-- Generated at: ${generatedAt} -->`,
    "",
    "# Recall Context",
    "",
    `Repo: \`${repo}\``,
    "",
    "Read this file before making repo-specific assumptions.",
    "",
    compiled,
    "",
  ].join("\n");
}

export function writeRepoContextArtifact(
  db: RecallDb,
  input: { repo?: string | null; repo_path?: string | null },
): RepoContextArtifactResult {
  const repo = input.repo ?? inferRepoSlugFromPath(input.repo_path) ?? null;
  const repoPath = input.repo_path ?? (repo ? resolveLocalRepoPath(repo) : null);

  if (!repo || !repoPath) {
    return {
      repo,
      repo_path: repoPath,
      output_path: null,
      written: false,
    };
  }

  const outputPath = getRepoContextArtifactPath(repoPath);
  mkdirSync(join(repoPath, ".recall"), { recursive: true });
  ensureRepoContextExcluded(repoPath);

  const content = renderRepoContextArtifact(db, repo);
  const existing = existsSync(outputPath) ? readFileSync(outputPath, "utf-8") : null;
  if (existing !== content) {
    writeFileSync(outputPath, content);
  }

  return {
    repo,
    repo_path: repoPath,
    output_path: outputPath,
    written: existing !== content,
  };
}

function ensureRepoContextExcluded(repoPath: string): void {
  try {
    const excludePath = execFileSync(
      "git",
      ["-C", repoPath, "rev-parse", "--git-path", "info/exclude"],
      { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    if (!excludePath) return;

    const existing = existsSync(excludePath) ? readFileSync(excludePath, "utf-8") : "";
    if (existing.split("\n").some((line) => line.trim() === ".recall/")) return;

    const prefix = existing && !existing.endsWith("\n") ? "\n" : "";
    writeFileSync(
      excludePath,
      `${existing}${prefix}# Recall generated context\n.recall/\n`,
    );
  } catch {
    // ignore if repo is not a standard git checkout
  }
}
