import { compileContext } from "../compiler/context.js";
import type { RecallDb } from "../db/client.js";

export function exportMarkdown(db: RecallDb, repo: string): string {
  const result = compileContext(db, { repo });
  if (!result.text) {
    return `# ${repo}\n\nNo active memories above confidence threshold.\n`;
  }
  return result.text;
}

export function exportClaude(db: RecallDb, repo: string): string {
  const result = compileContext(db, { repo });
  if (!result.text) return "";

  return `# CLAUDE.md — Auto-generated by Recall
# Do not edit manually. Run \`recall export -r ${repo} -f claude\` to regenerate.

${result.text}`;
}

export function exportCodex(db: RecallDb, repo: string): string {
  const result = compileContext(db, { repo });
  if (!result.text) return "";

  return `# AGENTS.md — Auto-generated by Recall
# Do not edit manually. Run \`recall export -r ${repo} -f codex\` to regenerate.

${result.text}`;
}
