import { execFileSync } from "node:child_process";
import {
  existsSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, parse, resolve } from "node:path";
import { getRepoContextArtifactPath } from "../artifacts/context.js";
import {
  uninstallClaudeCodeHooks,
  uninstallClaudeCodeMemoryOverride,
} from "../agents/claude-code.js";
import { uninstallCodexHooks } from "../agents/codex.js";
import { isHooklessAgent, listAgentNames, resolveAdapter } from "../agents/index.js";
import type { AgentName, InstallResult } from "../agents/types.js";
import {
  deleteApiKey,
  hasKeychainApiKey,
  type LlmProvider,
} from "../credentials/keychain.js";
import { closeDb } from "../db/client.js";
import {
  defaultServiceLabel,
  uninstallService,
} from "../daemon/service.js";
import { discoverLocalRepos } from "../repo/discovery.js";

const GENERATED_CONTEXT_MARKER =
  "<!-- Auto-generated by Recall. Do not edit manually. -->";
const PROVIDERS: readonly LlmProvider[] = [
  "openai",
  "anthropic",
  "azure-openai",
];

export interface LocalDataPurgeOptions {
  dataDir?: string;
  dryRun?: boolean;
  homeDir?: string;
  keepIntegrations?: boolean;
  repoRoots?: string[];
}

export interface PurgeAction {
  category: "data" | "credential" | "artifact" | "integration" | "service";
  target: string;
  status: "planned" | "removed" | "absent" | "failed" | "retained";
  detail?: string;
}

export interface LocalDataPurgeResult {
  dry_run: boolean;
  data_dir: string;
  integrations_retained: boolean;
  actions: PurgeAction[];
  failures: number;
}

export function resolveRecallDataDir(
  options: Pick<LocalDataPurgeOptions, "dataDir" | "homeDir"> = {},
): string {
  const home = resolve(options.homeDir ?? homedir());
  return resolve(options.dataDir ?? process.env.RECALL_DATA_DIR ?? join(home, ".recall"));
}

export function purgeLocalData(
  options: LocalDataPurgeOptions = {},
): LocalDataPurgeResult {
  const dryRun = options.dryRun ?? false;
  const home = resolve(options.homeDir ?? homedir());
  const dataDir = resolveRecallDataDir({ dataDir: options.dataDir, homeDir: home });
  assertSafeDataDir(dataDir, home);

  const repoRoots = options.repoRoots ?? configuredRepoRoots(home);
  const actions: PurgeAction[] = [];
  const contextPaths = findGeneratedContextArtifacts(repoRoots);

  if (options.keepIntegrations) {
    actions.push({
      category: "integration",
      target: "agent hooks, rules, and MCP registrations",
      status: "retained",
      detail: "--keep-integrations",
    });
    actions.push({
      category: "service",
      target: defaultServiceLabel(),
      status: "retained",
      detail: "--keep-integrations",
    });
  } else if (dryRun) {
    actions.push(...plannedIntegrationActions(repoRoots));
  } else {
    actions.push(...removeIntegrations(repoRoots));
    actions.push(removeDaemonService());
  }

  for (const provider of PROVIDERS) {
    if (dryRun) {
      actions.push({
        category: "credential",
        target: `macOS Keychain ${provider}`,
        status: "planned",
      });
      continue;
    }
    const present = hasKeychainApiKey(provider);
    const removed = present ? deleteApiKey(provider) : false;
    actions.push({
      category: "credential",
      target: `macOS Keychain ${provider}`,
      status: removed ? "removed" : present ? "failed" : "absent",
      detail: present && !removed ? "credential still present" : undefined,
    });
  }

  for (const contextPath of contextPaths) {
    if (dryRun) {
      actions.push({
        category: "artifact",
        target: contextPath,
        status: "planned",
      });
      continue;
    }
    try {
      rmSync(contextPath, { force: true });
      removeDirectoryIfEmpty(dirname(contextPath));
      actions.push({
        category: "artifact",
        target: contextPath,
        status: "removed",
      });
    } catch (error) {
      actions.push(failed("artifact", contextPath, error));
    }
  }

  if (dryRun) {
    actions.push({
      category: "data",
      target: dataDir,
      status: existsSync(dataDir) ? "planned" : "absent",
      detail: "database, WAL, backups, logs, caches, models, and sync state",
    });
  } else {
    try {
      closeDb();
      const existed = existsSync(dataDir);
      rmSync(dataDir, { recursive: true, force: true });
      actions.push({
        category: "data",
        target: dataDir,
        status: existed ? "removed" : "absent",
        detail: "database, WAL, backups, logs, caches, models, and sync state",
      });
    } catch (error) {
      actions.push(failed("data", dataDir, error));
    }
  }

  return {
    dry_run: dryRun,
    data_dir: dataDir,
    integrations_retained: options.keepIntegrations ?? false,
    actions,
    failures: actions.filter((action) => action.status === "failed").length,
  };
}

function assertSafeDataDir(dataDir: string, home: string): void {
  const root = parse(dataDir).root;
  if (dataDir === root || dataDir === home) {
    throw new Error(`Refusing unsafe Recall data directory: ${dataDir}`);
  }
}

function configuredRepoRoots(home: string): string[] {
  const configured = process.env.RECALL_REPO_ROOTS
    ?.split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  return configured?.length
    ? configured.map((value) => resolve(value))
    : [join(home, "Projects")];
}

function findGeneratedContextArtifacts(repoRoots: string[]): string[] {
  const paths = new Set<string>();
  for (const repo of discoverLocalRepos(repoRoots)) {
    const candidate = getRepoContextArtifactPath(repo.repo_path);
    if (isGeneratedContext(candidate)) paths.add(candidate);
  }

  const cwdCandidate = getRepoContextArtifactPath(process.cwd());
  if (isGeneratedContext(cwdCandidate)) paths.add(cwdCandidate);
  return [...paths].sort();
}

function isGeneratedContext(path: string): boolean {
  if (!existsSync(path)) return false;
  try {
    return readFileSync(path, "utf8").startsWith(GENERATED_CONTEXT_MARKER);
  } catch {
    return false;
  }
}

function plannedIntegrationActions(repoRoots: string[]): PurgeAction[] {
  const actions: PurgeAction[] = [
    planned("service", defaultServiceLabel()),
    planned("integration", "Claude Code hooks, memory override, and Recall MCP"),
    planned("integration", "Codex hooks and Recall MCP"),
  ];
  for (const agent of listAgentNames().filter(isHooklessAgent)) {
    actions.push(planned("integration", `${agent} Recall MCP and managed rules`));
  }
  for (const repo of discoverLocalRepos(repoRoots)) {
    actions.push(planned("integration", `${repo.repo_path} managed Recall rules`));
  }
  return actions;
}

function removeIntegrations(repoRoots: string[]): PurgeAction[] {
  const actions: PurgeAction[] = [];
  actions.push(fromInstallResult(
    "Claude Code hooks",
    uninstallClaudeCodeHooks(),
  ));
  actions.push(fromInstallResult(
    "Claude Code memory override",
    uninstallClaudeCodeMemoryOverride(),
  ));
  actions.push(fromInstallResult("Codex hooks", uninstallCodexHooks()));

  actions.push(removeCliMcp("claude", ["mcp", "remove", "recall", "-s", "user"]));
  actions.push(removeCliMcp("codex", ["mcp", "remove", "recall"]));

  const hookless = listAgentNames().filter(isHooklessAgent);
  for (const name of hookless) {
    const adapter = resolveAdapter(name);
    if (adapter.removeMcpFallback) {
      actions.push(fromInstallResult(
        `${name} Recall MCP`,
        adapter.removeMcpFallback(),
      ));
    }
    if (adapter.rulesScope === "global" && adapter.uninstallRules) {
      actions.push(fromInstallResult(
        `${name} managed rules`,
        adapter.uninstallRules(),
      ));
    }
  }

  for (const repo of discoverLocalRepos(repoRoots)) {
    for (const name of hookless) {
      const adapter = resolveAdapter(name);
      if (adapter.rulesScope !== "project" || !adapter.uninstallRules) continue;
      actions.push(fromInstallResult(
        `${name} managed rules in ${repo.repo_path}`,
        adapter.uninstallRules({ cwd: repo.repo_path }),
      ));
    }
    actions.push(removeCliMcp(
      "claude",
      ["mcp", "remove", "recall", "-s", "project"],
      repo.repo_path,
    ));
  }

  return actions;
}

function removeCliMcp(
  command: "claude" | "codex",
  args: string[],
  cwd?: string,
): PurgeAction {
  const target = `${command} Recall MCP${cwd ? ` in ${cwd}` : ""}`;
  try {
    execFileSync(command, ["mcp", "get", "recall"], {
      cwd,
      stdio: "ignore",
      timeout: 10_000,
    });
  } catch {
    return {
      category: "integration",
      target,
      status: "absent",
      detail: "not registered or CLI unavailable",
    };
  }

  try {
    execFileSync(command, args, {
      cwd,
      stdio: "ignore",
      timeout: 10_000,
    });
    return { category: "integration", target, status: "removed" };
  } catch (error) {
    return {
      category: "integration",
      target,
      status: "failed",
      detail: error instanceof Error ? error.message : "MCP removal failed",
    };
  }
}

function removeDaemonService(): PurgeAction {
  const label = defaultServiceLabel();
  if (process.platform !== "darwin" && process.platform !== "linux") {
    return {
      category: "service",
      target: label,
      status: "absent",
      detail: `unsupported platform ${process.platform}`,
    };
  }
  try {
    const status = uninstallService(label);
    return {
      category: "service",
      target: label,
      status: status.installed || status.loaded ? "failed" : "removed",
      detail: status.installed || status.loaded
        ? "service still reports installed or loaded"
        : undefined,
    };
  } catch (error) {
    return failed("service", label, error);
  }
}

function planned(
  category: PurgeAction["category"],
  target: string,
): PurgeAction {
  return { category, target, status: "planned" };
}

function fromInstallResult(target: string, result: InstallResult): PurgeAction {
  return {
    category: "integration",
    target,
    status: result.ok ? (result.changed ? "removed" : "absent") : "failed",
    detail: result.message,
  };
}

function failed(
  category: PurgeAction["category"],
  target: string,
  error: unknown,
): PurgeAction {
  return {
    category,
    target,
    status: "failed",
    detail: error instanceof Error ? error.message : String(error),
  };
}

function removeDirectoryIfEmpty(path: string): void {
  try {
    if (readdirSync(path).length === 0) rmdirSync(path);
  } catch {
    // The directory may contain user-owned files. Leave it untouched.
  }
}
